//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiSoDienNuoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiSoDienNuoc()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.HoaDons1 = new HashSet<HoaDon>();
        }
    
        public string MaChiSo { get; set; }
        public string MaHopDong { get; set; }
        public string LoaiDichVu { get; set; }
        public System.DateTime ThangGhi { get; set; }
        public decimal ChiSoDau { get; set; }
        public decimal ChiSoCuoi { get; set; }
        public Nullable<decimal> SoTieuThu { get; set; }
        public decimal DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public string AnhDongHo { get; set; }
        public string NguoiGhiId { get; set; }
        public bool TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual HopDong HopDong { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons1 { get; set; }
    }
}
