//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaPhong
    {
        public string MaDanhGia { get; set; }
        public string MaHopDong { get; set; }
        public string MaKhachHang { get; set; }
        public string MaPhong { get; set; }
        public string NhanXet { get; set; }
        public byte DiemDanhGia { get; set; }
        public bool TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual HopDong HopDong { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual PhongTro PhongTro { get; set; }
    }
}
