//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaDichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiaDichVu()
        {
            this.HopDong_DichVu = new HashSet<HopDong_DichVu>();
        }
    
        public string MaGiaDichVu { get; set; }
        public string MaToaNha { get; set; }
        public string MaTienIch { get; set; }
        public string TenDichVu { get; set; }
        public string DonVi { get; set; }
        public decimal DonGia { get; set; }
        public System.DateTime NgayApDung { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public bool TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual TienIch TienIch { get; set; }
        public virtual ToaNha ToaNha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong_DichVu> HopDong_DichVu { get; set; }
    }
}
