//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyHouse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HappyHouseEntities : DbContext
    {
        public HappyHouseEntities()
            : base("name=HappyHouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiSoDienNuoc> ChiSoDienNuocs { get; set; }
        public virtual DbSet<ChuDeTinTuc> ChuDeTinTucs { get; set; }
        public virtual DbSet<DanhGiaPhong> DanhGiaPhongs { get; set; }
        public virtual DbSet<GiaDichVu> GiaDichVus { get; set; }
        public virtual DbSet<HinhAnhPhong> HinhAnhPhongs { get; set; }
        public virtual DbSet<HinhAnhToaNha> HinhAnhToaNhas { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<HopDong> HopDongs { get; set; }
        public virtual DbSet<HopDong_DichVu> HopDong_DichVu { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<PhongTro> PhongTroes { get; set; }
        public virtual DbSet<ThanhToan> ThanhToans { get; set; }
        public virtual DbSet<ThongBao> ThongBaos { get; set; }
        public virtual DbSet<TienIch> TienIches { get; set; }
        public virtual DbSet<TinTuc> TinTucs { get; set; }
        public virtual DbSet<ToaNha> ToaNhas { get; set; }
        public virtual DbSet<VaiTro> VaiTroes { get; set; }
    }
}
