//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnhPhong
    {
        public int MaHinhAnh { get; set; }
        public string MaPhong { get; set; }
        public string TenFile { get; set; }
        public bool LaDaiDien { get; set; }
        public bool TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual PhongTro PhongTro { get; set; }
    }
}
