//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.ThanhToans = new HashSet<ThanhToan>();
        }
    
        public string MaHoaDon { get; set; }
        public string MaHopDong { get; set; }
        public System.DateTime ThangHoaDon { get; set; }
        public string MaChiSoDien { get; set; }
        public string MaChiSoNuoc { get; set; }
        public decimal TienPhong { get; set; }
        public decimal TienDien { get; set; }
        public decimal TienNuoc { get; set; }
        public decimal TienDichVu { get; set; }
        public decimal TongTien { get; set; }
        public System.DateTime HanThanhToan { get; set; }
        public string GhiChu { get; set; }
        public string TrangThaiHoaDon { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public bool TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual ChiSoDienNuoc ChiSoDienNuoc { get; set; }
        public virtual ChiSoDienNuoc ChiSoDienNuoc1 { get; set; }
        public virtual HopDong HopDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
    }
}
