//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDong()
        {
            this.ChiSoDienNuocs = new HashSet<ChiSoDienNuoc>();
            this.DanhGiaPhongs = new HashSet<DanhGiaPhong>();
            this.HoaDons = new HashSet<HoaDon>();
            this.HopDong_DichVu = new HashSet<HopDong_DichVu>();
        }
    
        public string MaHopDong { get; set; }
        public string MaPhong { get; set; }
        public string MaKhachHang { get; set; }
        public string MaChuTro { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public decimal GiaThueThang { get; set; }
        public Nullable<decimal> TienCoc { get; set; }
        public int NgayThanhToanHangThang { get; set; }
        public string DieuKhoan { get; set; }
        public string FileHopDong { get; set; }
        public string TrangThaiHopDong { get; set; }
        public Nullable<System.DateTime> NgayHuy { get; set; }
        public string LyDoHuy { get; set; }
        public bool TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiSoDienNuoc> ChiSoDienNuocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaPhong> DanhGiaPhongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
        public virtual PhongTro PhongTro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong_DichVu> HopDong_DichVu { get; set; }
    }
}
