//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongTro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhongTro()
        {
            this.DanhGiaPhongs = new HashSet<DanhGiaPhong>();
            this.HinhAnhPhongs = new HashSet<HinhAnhPhong>();
            this.HopDongs = new HashSet<HopDong>();
            this.TienIches = new HashSet<TienIch>();
        }
    
        public string MaPhong { get; set; }
        public string MaToaNha { get; set; }
        public string SoPhong { get; set; }
        public int Tang { get; set; }
        public Nullable<decimal> DienTich { get; set; }
        public decimal GiaThue { get; set; }
        public Nullable<decimal> TienCoc { get; set; }
        public int SoNguoiToiDa { get; set; }
        public string MoTa { get; set; }
        public string TrangThaiPhong { get; set; }
        public bool TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaPhong> DanhGiaPhongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnhPhong> HinhAnhPhongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong> HopDongs { get; set; }
        public virtual ToaNha ToaNha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TienIch> TienIches { get; set; }
    }
}
