//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public string MaThanhToan { get; set; }
        public string MaHoaDon { get; set; }
        public string MaKhachHang { get; set; }
        public decimal SoTien { get; set; }
        public string HinhThuc { get; set; }
        public string MaGiaoDich { get; set; }
        public string AnhBienLai { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime NgayThanhToan { get; set; }
        public string NguoiXacNhanId { get; set; }
        public string TrangThaiXacNhan { get; set; }
        public string LyDoTuChoi { get; set; }
        public bool TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
    }
}
