//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public string MaTinTuc { get; set; }
        public string MaChuDe { get; set; }
        public string MaNguoiDang { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public string AnhDaiDien { get; set; }
        public string TomTat { get; set; }
        public int LuotXem { get; set; }
        public string TrangThaiDang { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public bool TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual ChuDeTinTuc ChuDeTinTuc { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
