//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToaNha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToaNha()
        {
            this.GiaDichVus = new HashSet<GiaDichVu>();
            this.HinhAnhToaNhas = new HashSet<HinhAnhToaNha>();
            this.PhongTroes = new HashSet<PhongTro>();
        }
    
        public string MaToaNha { get; set; }
        public string MaChuTro { get; set; }
        public string TenToaNha { get; set; }
        public string DiaChi { get; set; }
        public string PhuongXa { get; set; }
        public string TinhThanh { get; set; }
        public string MoTa { get; set; }
        public string TrangThaiDuyet { get; set; }
        public string LyDoTuChoi { get; set; }
        public string MaNguoiDuyet { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public bool TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaDichVu> GiaDichVus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnhToaNha> HinhAnhToaNhas { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhongTro> PhongTroes { get; set; }
    }
}
